debug: true

spring:
  application:
    name: LoginService
  datasource:
    url: jdbc:h2:mem:tenth
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: {{Tenth.ClientId.Secret}}
            clientSecret: {{Tenth.ClientSecret.Secret}}
  cloud:
    inetutils:
      preferredNetworks: 192.168.1,96.39
    client:
      hostname: ${tenth.srvhost}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${tenth.srvhost}:8761/eureka
    instance:
      hostname: ${tenth.srvhost}
      preferIpAddress: true

tenth:
  srvhost: DESKTOP-4NACQ64